import type { AssessmentCatalogueDefinition } from './assessment-catalogue-types'

const individualAssessmentPath = '/assessment/workspace'

export const assessmentCatalogueDefinitions: AssessmentCatalogueDefinition[] = [
  {
    id: 'signals',
    slug: 'sonartra-signals',
    title: 'Sonartra Signals',
    category: 'individual',
    shortDescription: 'Baseline individual diagnostic for behavioural signal capture, leadership tendencies, and operating style interpretation.',
    longDescription:
      'Capture a structured behavioural baseline across the core Sonartra signal model. This assessment establishes the reference profile used across individual intelligence outputs and downstream coaching interpretation.',
    measures: ['Behaviour style', 'Motivators', 'Leadership', 'Conflict', 'Culture', 'Stress'],
    estimatedMinutes: 10,
    questionCount: 80,
    hasAdvancedOutputs: false,
    defaultOperationalDetails: [
      { label: 'Question set', value: '80 scored items across six signal layers' },
      { label: 'Typical runtime', value: '10 minutes for a full uninterrupted pass' },
      { label: 'Cadence', value: 'Recommended quarterly or after major role change' },
    ],
    defaultAccessRows: [
      { label: 'Access', value: 'Assigned to all active users on current plan' },
      { label: 'Entry point', value: 'Launches the live assessment workspace with resume support' },
    ],
    defaultStatusNotes: {
      complete: 'Retaking this assessment creates a new results snapshot while preserving previous completed snapshots for reference.',
    },
    isRetakeAllowed: true,
    displayOrder: 0,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'live',
    assessmentHref: individualAssessmentPath,
    resultsHref: '/results/individual',
  },
  {
    id: 'leadership-effectiveness',
    slug: 'leadership-effectiveness',
    title: 'Leadership Effectiveness',
    category: 'individual',
    shortDescription: 'Assess day-to-day leadership execution, delegation discipline, feedback habits, and decision follow-through.',
    longDescription:
      'Evaluate how leadership intent translates into execution rhythm, accountability, and managerial follow-through. Designed for operators who need a concise read on how they lead under normal delivery pressure.',
    measures: ['Delegation', 'Feedback quality', 'Execution discipline', 'Decision follow-through'],
    estimatedMinutes: 12,
    questionCount: 36,
    hasAdvancedOutputs: false,
    defaultOperationalDetails: [
      { label: 'Question set', value: '36 scored items with short-form completion flow' },
      { label: 'Typical runtime', value: '12 minutes with no external preparation required' },
      { label: 'Best used when', value: 'Preparing for manager coaching or role calibration' },
    ],
    defaultAccessRows: [
      { label: 'Access', value: 'Available to individual users with leadership track enabled' },
      { label: 'Launch mode', value: 'Starts a new attempt and autosaves progress by question' },
    ],
    defaultStatusNotes: {},
    isRetakeAllowed: false,
    displayOrder: 1,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'live',
    assessmentHref: '#',
  },
  {
    id: 'burnout-risk',
    slug: 'burnout-risk',
    title: 'Burnout Risk',
    category: 'individual',
    shortDescription: 'Track workload strain, energy depletion, and recovery risk before productivity and judgment degrade further.',
    longDescription:
      'Identify pressure accumulation patterns affecting resilience, concentration, and decision quality. The workflow is optimised for repeat check-ins when capacity risk needs active monitoring.',
    measures: ['Workload strain', 'Recovery debt', 'Energy variability', 'Focus erosion'],
    estimatedMinutes: 8,
    questionCount: 32,
    hasAdvancedOutputs: false,
    defaultOperationalDetails: [
      { label: 'Question set', value: '32 scored items with weighted recovery and strain markers' },
      { label: 'Typical runtime', value: '8 minutes with focused pulse-check completion' },
      { label: 'Recommended cadence', value: 'Use during periods of sustained delivery pressure' },
    ],
    defaultAccessRows: [
      { label: 'Access', value: 'Assigned to users enrolled in resilience monitoring workflows' },
      { label: 'Launch mode', value: 'Resumes from latest saved response state' },
    ],
    defaultStatusNotes: {
      in_progress: 'Progress is active. Resuming continues from the latest autosaved response rather than restarting the instrument.',
    },
    isRetakeAllowed: false,
    displayOrder: 2,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'live',
    assessmentHref: '#',
  },
  {
    id: 'conflict-style',
    slug: 'conflict-style',
    title: 'Conflict Style',
    category: 'individual',
    shortDescription: 'Map how tension is handled under disagreement, escalation, negotiation pressure, and resolution cycles.',
    longDescription:
      'Surface the response patterns most likely to show up when decisions stall, ownership overlaps, or stakes increase. Useful for coaching working relationships and improving escalation quality.',
    measures: ['Escalation response', 'Collaboration under strain', 'Negotiation posture', 'Resolution bias'],
    estimatedMinutes: 9,
    questionCount: 28,
    hasAdvancedOutputs: false,
    defaultOperationalDetails: [
      { label: 'Question set', value: '28 scored items with situational response comparisons' },
      { label: 'Typical runtime', value: '9 minutes with concise scenario-based prompts' },
      { label: 'Best used when', value: 'Coaching partnerships, team friction, or role handoffs' },
    ],
    defaultAccessRows: [
      { label: 'Access', value: 'Available within the individual insight library' },
      { label: 'Launch mode', value: 'Starts a fresh attempt and records progress automatically' },
    ],
    defaultStatusNotes: {},
    isRetakeAllowed: false,
    displayOrder: 3,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'live',
    assessmentHref: '#',
  },
  {
    id: 'decision-profile',
    slug: 'decision-profile',
    title: 'Decision Profile',
    category: 'individual',
    shortDescription: 'Forthcoming diagnostic for judgment pace, evidence thresholds, and operating trade-off patterns.',
    longDescription:
      'This diagnostic is being prepared for release and will profile how decisions are framed, accelerated, and revised under uncertainty. Availability will be announced once the instrument is production ready.',
    measures: ['Evidence threshold', 'Decision speed', 'Risk tolerance', 'Revision discipline'],
    estimatedMinutes: 10,
    questionCount: 30,
    hasAdvancedOutputs: false,
    defaultOperationalDetails: [
      { label: 'Question set', value: '30-item planned release configuration' },
      { label: 'Typical runtime', value: 'Approximately 10 minutes when available' },
      { label: 'Release state', value: 'Instrument is configured but not yet enabled for launch' },
    ],
    defaultAccessRows: [
      { label: 'Access', value: 'Not currently available on any plan tier' },
      { label: 'Launch mode', value: 'No active entry point until release is enabled' },
    ],
    defaultStatusNotes: {
      coming_soon: 'This assessment is not yet available. Launch controls are intentionally withheld until release readiness is confirmed.',
    },
    isRetakeAllowed: false,
    displayOrder: 4,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'coming_soon',
  },
  {
    id: 'team-dynamics',
    slug: 'team-dynamics',
    title: 'Team Dynamics',
    category: 'team',
    shortDescription: 'Evaluate cohesion, communication quality, role clarity, and friction patterns across a working team.',
    longDescription:
      'Provide a team-level diagnostic of how members coordinate, challenge, and recover under operating pressure. Suitable for recurring pulse cycles and intervention planning with leadership teams.',
    measures: ['Cohesion', 'Role clarity', 'Communication quality', 'Friction management'],
    estimatedMinutes: 15,
    questionCount: 40,
    hasAdvancedOutputs: true,
    defaultOperationalDetails: [
      { label: 'Question set', value: '40 scored items administered across team participants' },
      { label: 'Typical runtime', value: '15 minutes per participant' },
      { label: 'Administration', value: 'Designed for managed team rollout rather than solo completion' },
    ],
    defaultAccessRows: [
      { label: 'Access', value: 'Available to team administrators and eligible managers' },
      { label: 'Launch mode', value: 'Creates a team campaign with participant invites and tracking' },
    ],
    defaultStatusNotes: {},
    isRetakeAllowed: false,
    displayOrder: 5,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'live',
    assessmentHref: '#',
  },
  {
    id: 'team-alignment',
    slug: 'team-alignment',
    title: 'Team Alignment',
    category: 'team',
    shortDescription: 'Measure strategic alignment, priority clarity, and execution consistency across shared workstreams.',
    longDescription:
      'Assess whether the team is operating from the same priorities, trade-off logic, and execution assumptions. This instrument helps isolate where alignment breaks down between strategy and delivery.',
    measures: ['Priority clarity', 'Decision alignment', 'Execution consistency', 'Shared direction'],
    estimatedMinutes: 14,
    questionCount: 34,
    hasAdvancedOutputs: false,
    defaultOperationalDetails: [
      { label: 'Question set', value: '34 scored items focused on shared strategic execution' },
      { label: 'Typical runtime', value: '14 minutes per participant' },
      { label: 'Best used when', value: 'Teams are re-scoping priorities or resetting execution rhythm' },
    ],
    defaultAccessRows: [
      { label: 'Access', value: 'Available within the team assessment repository' },
      { label: 'Launch mode', value: 'Starts a managed team invitation cycle' },
    ],
    defaultStatusNotes: {},
    isRetakeAllowed: false,
    displayOrder: 6,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'live',
    assessmentHref: '#',
  },
  {
    id: 'manager-effectiveness',
    slug: 'manager-effectiveness',
    title: 'Manager Effectiveness',
    category: 'team',
    shortDescription: 'Surface team-observed patterns in manager clarity, support, direction, and follow-through quality.',
    longDescription:
      'Collect team-level perception data on managerial effectiveness across clarity, support, accountability, and communication consistency. Best suited for development planning and manager calibration cycles.',
    measures: ['Clarity', 'Support quality', 'Manager consistency', 'Follow-through'],
    estimatedMinutes: 12,
    questionCount: 30,
    hasAdvancedOutputs: true,
    defaultOperationalDetails: [
      { label: 'Question set', value: '30 scored items distributed to team respondents' },
      { label: 'Typical runtime', value: '12 minutes per participant' },
      { label: 'Administration', value: 'Runs as a managed team survey with consolidated reporting' },
    ],
    defaultAccessRows: [
      { label: 'Access', value: 'Enabled for team plans with manager review workflows' },
      { label: 'Launch mode', value: 'Starts a managed distribution and collection cycle' },
    ],
    defaultStatusNotes: {},
    isRetakeAllowed: false,
    displayOrder: 7,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'live',
    assessmentHref: '#',
  },
  {
    id: 'culture-risk',
    slug: 'culture-risk',
    title: 'Culture Risk',
    category: 'team',
    shortDescription: 'Identify emerging cultural risk signals affecting trust, accountability, and execution reliability.',
    longDescription:
      'Detect pressure points where trust, accountability, and behavioural norms are diverging from expected operating standards. Intended for teams requiring an early-warning culture diagnostic rather than a broad engagement survey.',
    measures: ['Trust stability', 'Norm adherence', 'Accountability', 'Execution reliability'],
    estimatedMinutes: 16,
    questionCount: 42,
    hasAdvancedOutputs: true,
    defaultOperationalDetails: [
      { label: 'Question set', value: '42 scored items calibrated for emerging risk detection' },
      { label: 'Typical runtime', value: '16 minutes per participant' },
      { label: 'Best used when', value: 'Investigating delivery friction or cultural drift signals' },
    ],
    defaultAccessRows: [
      { label: 'Access', value: 'Available to teams with advanced organisational diagnostics enabled' },
      { label: 'Launch mode', value: 'Starts a managed collection wave with participation tracking' },
    ],
    defaultStatusNotes: {},
    isRetakeAllowed: false,
    displayOrder: 8,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'live',
    assessmentHref: '#',
  },
  {
    id: 'decision-friction-mapping',
    slug: 'decision-friction-mapping',
    title: 'Decision Friction Mapping',
    category: 'team',
    shortDescription: 'Upcoming team instrument for locating bottlenecks, escalation drag, and decision ownership ambiguity.',
    longDescription:
      'This team diagnostic is in preparation and will map where decision flow stalls across teams, managers, and operating forums. It is not currently launchable and will appear once release criteria are met.',
    measures: ['Ownership clarity', 'Escalation drag', 'Decision latency', 'Approval bottlenecks'],
    estimatedMinutes: 13,
    questionCount: 36,
    hasAdvancedOutputs: false,
    defaultOperationalDetails: [
      { label: 'Question set', value: '36-item planned release configuration' },
      { label: 'Typical runtime', value: '13 minutes per participant when available' },
      { label: 'Release state', value: 'Instrument is staged but not enabled for active campaigns' },
    ],
    defaultAccessRows: [
      { label: 'Access', value: 'Not yet available for launch' },
      { label: 'Launch mode', value: 'Entry point will appear after release activation' },
    ],
    defaultStatusNotes: {
      coming_soon: 'This assessment is not yet available. Campaign launch remains unavailable until the instrument is released.',
    },
    isRetakeAllowed: false,
    displayOrder: 9,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'coming_soon',
  },
  {
    id: 'shadow-archived-team-health',
    slug: 'team-health-archive',
    title: 'Team Health Archive',
    category: 'team',
    shortDescription: 'Archived internal instrument used to validate selector exclusions.',
    longDescription: 'Archived item retained only to prove repository filtering rules before an admin console exists.',
    measures: ['Archive'],
    estimatedMinutes: 5,
    questionCount: 10,
    hasAdvancedOutputs: false,
    defaultOperationalDetails: [{ label: 'State', value: 'Archived from active repository' }],
    defaultAccessRows: [{ label: 'Access', value: 'Hidden from repository' }],
    defaultStatusNotes: {},
    isRetakeAllowed: false,
    displayOrder: 99,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'archived',
    assessmentHref: '#',
  },
  {
    id: 'shadow-hidden-role-fit',
    slug: 'role-fit-hidden',
    title: 'Role Fit Pilot',
    category: 'individual',
    shortDescription: 'Hidden pilot item used to validate repository visibility logic.',
    longDescription: 'Hidden item retained only to prove repository filtering rules before an admin console exists.',
    measures: ['Pilot'],
    estimatedMinutes: 7,
    questionCount: 18,
    hasAdvancedOutputs: false,
    defaultOperationalDetails: [{ label: 'State', value: 'Hidden pilot' }],
    defaultAccessRows: [{ label: 'Access', value: 'Explicitly hidden from repository' }],
    defaultStatusNotes: {},
    isRetakeAllowed: false,
    displayOrder: 98,
    isPublished: true,
    isVisibleInRepository: true,
    releaseState: 'live',
    assessmentHref: '#',
  },
]
