import type { AssessmentProgressState } from './assessment-catalogue-types'

export const assessmentProgressState: AssessmentProgressState[] = [
  {
    assessmentId: 'signals',
    subjectType: 'user',
    subjectId: 'user-current',
    hasActiveAttempt: false,
    progressPercent: 100,
    startedAt: '2026-03-15T09:18:00.000Z',
    lastSavedAt: '2026-03-15T09:29:30.000Z',
    hasCompletedResult: true,
    completedAt: '2026-03-15T09:30:00.000Z',
    latestResultId: 'result-signals-latest',
    latestAttemptId: 'attempt-signals-latest',
    resultsAvailable: true,
  },
  {
    assessmentId: 'burnout-risk',
    subjectType: 'user',
    subjectId: 'user-current',
    hasActiveAttempt: true,
    progressPercent: 42,
    startedAt: '2026-03-18T16:12:00.000Z',
    lastSavedAt: '2026-03-18T16:19:00.000Z',
    hasCompletedResult: false,
    completedAt: null,
    latestResultId: null,
    latestAttemptId: 'attempt-burnout-current',
    resultsAvailable: false,
  },
  {
    assessmentId: 'team-dynamics',
    subjectType: 'team',
    subjectId: 'team-core',
    hasActiveAttempt: false,
    progressPercent: 0,
    startedAt: null,
    lastSavedAt: null,
    hasCompletedResult: false,
    completedAt: null,
    latestResultId: null,
    latestAttemptId: null,
    resultsAvailable: false,
  },
  {
    assessmentId: 'team-alignment',
    subjectType: 'team',
    subjectId: 'team-core',
    hasActiveAttempt: false,
    progressPercent: 0,
    startedAt: null,
    lastSavedAt: null,
    hasCompletedResult: false,
    completedAt: null,
    latestResultId: null,
    latestAttemptId: null,
    resultsAvailable: false,
  },
  {
    assessmentId: 'manager-effectiveness',
    subjectType: 'team',
    subjectId: 'team-core',
    hasActiveAttempt: false,
    progressPercent: 0,
    startedAt: null,
    lastSavedAt: null,
    hasCompletedResult: false,
    completedAt: null,
    latestResultId: null,
    latestAttemptId: null,
    resultsAvailable: false,
  },
  {
    assessmentId: 'culture-risk',
    subjectType: 'team',
    subjectId: 'team-core',
    hasActiveAttempt: false,
    progressPercent: 0,
    startedAt: null,
    lastSavedAt: null,
    hasCompletedResult: false,
    completedAt: null,
    latestResultId: null,
    latestAttemptId: null,
    resultsAvailable: false,
  },
]
