import type { AssessmentAvailabilityConfig } from './assessment-catalogue-types'

export const assessmentAvailabilityConfig: AssessmentAvailabilityConfig[] = [
  {
    assessmentId: 'signals',
    availabilityScope: 'all',
    allowedWorkspaceIds: [],
    allowedUserIds: [],
    allowedRoles: [],
    isEnabled: true,
    isHidden: false,
  },
  {
    assessmentId: 'leadership-effectiveness',
    availabilityScope: 'role',
    allowedWorkspaceIds: [],
    allowedUserIds: [],
    allowedRoles: ['manager', 'admin'],
    isEnabled: true,
    isHidden: false,
    fullAccessPlanRequirement: 'growth',
  },
  {
    assessmentId: 'burnout-risk',
    availabilityScope: 'user',
    allowedWorkspaceIds: [],
    allowedUserIds: ['user-current'],
    allowedRoles: [],
    isEnabled: true,
    isHidden: false,
  },
  {
    assessmentId: 'conflict-style',
    availabilityScope: 'all',
    allowedWorkspaceIds: [],
    allowedUserIds: [],
    allowedRoles: [],
    isEnabled: true,
    isHidden: false,
  },
  {
    assessmentId: 'decision-profile',
    availabilityScope: 'all',
    allowedWorkspaceIds: [],
    allowedUserIds: [],
    allowedRoles: [],
    isEnabled: true,
    isHidden: false,
    fullAccessPlanRequirement: 'growth',
  },
  {
    assessmentId: 'team-dynamics',
    availabilityScope: 'workspace',
    allowedWorkspaceIds: ['workspace-alpha'],
    allowedUserIds: [],
    allowedRoles: [],
    isEnabled: true,
    isHidden: false,
    advancedOutputsPlanRequirement: 'enterprise',
    fullAccessPlanRequirement: 'growth',
  },
  {
    assessmentId: 'team-alignment',
    availabilityScope: 'workspace',
    allowedWorkspaceIds: ['workspace-alpha'],
    allowedUserIds: [],
    allowedRoles: [],
    isEnabled: true,
    isHidden: false,
    fullAccessPlanRequirement: 'growth',
  },
  {
    assessmentId: 'manager-effectiveness',
    availabilityScope: 'role',
    allowedWorkspaceIds: [],
    allowedUserIds: [],
    allowedRoles: ['manager', 'admin'],
    isEnabled: true,
    isHidden: false,
    advancedOutputsPlanRequirement: 'enterprise',
    fullAccessPlanRequirement: 'growth',
  },
  {
    assessmentId: 'culture-risk',
    availabilityScope: 'workspace',
    allowedWorkspaceIds: ['workspace-alpha'],
    allowedUserIds: [],
    allowedRoles: [],
    isEnabled: true,
    isHidden: false,
    advancedOutputsPlanRequirement: 'enterprise',
    fullAccessPlanRequirement: 'enterprise',
  },
  {
    assessmentId: 'decision-friction-mapping',
    availabilityScope: 'workspace',
    allowedWorkspaceIds: ['workspace-alpha'],
    allowedUserIds: [],
    allowedRoles: [],
    isEnabled: true,
    isHidden: false,
    fullAccessPlanRequirement: 'enterprise',
  },
  {
    assessmentId: 'shadow-archived-team-health',
    availabilityScope: 'workspace',
    allowedWorkspaceIds: ['workspace-alpha'],
    allowedUserIds: [],
    allowedRoles: [],
    isEnabled: true,
    isHidden: false,
  },
  {
    assessmentId: 'shadow-hidden-role-fit',
    availabilityScope: 'all',
    allowedWorkspaceIds: [],
    allowedUserIds: [],
    allowedRoles: [],
    isEnabled: true,
    isHidden: true,
  },
]
