export const ASSESSMENT_LAYER_KEYS = [
  'behaviour_style',
  'motivators',
  'leadership',
  'conflict',
  'risk',
  'culture',
] as const;

export const WPLP80_SCORING_MODEL_KEY = 'wplp80-signal-model-v1' as const;

export const RESPONSE_QUALITY_STATUSES = ['normal', 'review'] as const;

export const RESPONSE_QUALITY_FLAGS = [
  'very_fast_completion',
  'sparse_timing_data',
  'long_idle_gap_detected',
  'high_rapid_response_count',
] as const;

export const WPLP80_SIGNAL_KEYS = [
  'Conflict_Accommodate',
  'Conflict_Avoid',
  'Conflict_Collaborate',
  'Conflict_Compete',
  'Conflict_Compromise',
  'Contribution_Analyse',
  'Contribution_Connect',
  'Contribution_Drive',
  'Contribution_Stabilise',
  'Core_Analyst',
  'Core_Driver',
  'Core_Influencer',
  'Core_Stabiliser',
  'Culture_Adhocracy',
  'Culture_Clan',
  'Culture_Hierarchy',
  'Culture_Market',
  'Decision_Evidence',
  'Decision_Opportunity',
  'Decision_Social',
  'Decision_Stability',
  'Integrity_Analyst',
  'Integrity_Driver',
  'Integrity_Influencer',
  'Integrity_Stabiliser',
  'Leader_People',
  'Leader_Process',
  'Leader_Results',
  'Leader_Vision',
  'Mot_Achievement',
  'Mot_Influence',
  'Mot_Mastery',
  'Mot_Stability',
  'Need_Authority',
  'Need_Belonging',
  'Need_Competence',
  'Need_Influence',
  'Stress_Avoidance',
  'Stress_Control',
  'Stress_Criticality',
  'Stress_Scatter',
  'Style_Analyst',
  'Style_Driver',
  'Style_Influencer',
  'Style_Stabiliser',
] as const;

export const SIGNAL_CODE_TO_LAYER: Record<string, (typeof ASSESSMENT_LAYER_KEYS)[number]> = {
  Core_Analyst: 'behaviour_style',
  Core_Driver: 'behaviour_style',
  Core_Influencer: 'behaviour_style',
  Core_Stabiliser: 'behaviour_style',
  Style_Analyst: 'behaviour_style',
  Style_Driver: 'behaviour_style',
  Style_Influencer: 'behaviour_style',
  Style_Stabiliser: 'behaviour_style',
  Contribution_Analyse: 'behaviour_style',
  Contribution_Connect: 'behaviour_style',
  Contribution_Drive: 'behaviour_style',
  Contribution_Stabilise: 'behaviour_style',

  Mot_Achievement: 'motivators',
  Mot_Influence: 'motivators',
  Mot_Mastery: 'motivators',
  Mot_Stability: 'motivators',
  Need_Authority: 'motivators',
  Need_Belonging: 'motivators',
  Need_Competence: 'motivators',
  Need_Influence: 'motivators',

  Leader_People: 'leadership',
  Leader_Process: 'leadership',
  Leader_Results: 'leadership',
  Leader_Vision: 'leadership',
  Integrity_Analyst: 'leadership',
  Integrity_Driver: 'leadership',
  Integrity_Influencer: 'leadership',
  Integrity_Stabiliser: 'leadership',

  Conflict_Accommodate: 'conflict',
  Conflict_Avoid: 'conflict',
  Conflict_Collaborate: 'conflict',
  Conflict_Compete: 'conflict',
  Conflict_Compromise: 'conflict',

  Decision_Evidence: 'risk',
  Decision_Opportunity: 'risk',
  Decision_Social: 'risk',
  Decision_Stability: 'risk',
  Stress_Avoidance: 'risk',
  Stress_Control: 'risk',
  Stress_Criticality: 'risk',
  Stress_Scatter: 'risk',

  Culture_Adhocracy: 'culture',
  Culture_Clan: 'culture',
  Culture_Hierarchy: 'culture',
  Culture_Market: 'culture',
};
