import { Assessment, AssessmentCategory, AssessmentStatus, AssessmentVersion, AssessmentVersionStatus, PublishStatus, PublishTargetType } from './assessments'
import { AuditAction, AuditEntityType, AuditLogEvent } from './audit'
import { Organisation, OrganisationMembership, OrganisationPlan, OrganisationRole, OrganisationStatus } from './organisations'
import { AdminCapability, AdminModuleKey, InternalAdminRole } from './roles'
import { User, UserKind, UserStatus } from './users'

export const adminUsers: User[] = [
  {
    id: 'user-admin-rina',
    externalAuthId: 'clerk_rina',
    email: 'rina.patel@sonartra.com',
    status: UserStatus.Active,
    kind: UserKind.InternalAdmin,
    profile: { firstName: 'Rina', lastName: 'Patel', fullName: 'Rina Patel', title: 'Director of Platform Operations', avatarUrl: null },
    internalAdminRole: InternalAdminRole.SuperAdmin,
    primaryOrganisationId: null,
    recentActivity: { lastActiveAt: '2026-03-20T07:18:00Z', lastAuditEventId: 'audit-1008', lastAssessmentVersionId: 'av-signals-2-2' },
    createdAt: '2025-07-02T08:00:00Z',
    updatedAt: '2026-03-20T07:18:00Z',
  },
  {
    id: 'user-admin-noah',
    externalAuthId: 'clerk_noah',
    email: 'noah.chen@sonartra.com',
    status: UserStatus.Active,
    kind: UserKind.InternalAdmin,
    profile: { firstName: 'Noah', lastName: 'Chen', fullName: 'Noah Chen', title: 'Assessment Operations Lead', avatarUrl: null },
    internalAdminRole: InternalAdminRole.AssessmentAdmin,
    primaryOrganisationId: null,
    recentActivity: { lastActiveAt: '2026-03-19T21:40:00Z', lastAuditEventId: 'audit-1007', lastAssessmentVersionId: 'av-team-1-1' },
    createdAt: '2025-09-11T09:30:00Z',
    updatedAt: '2026-03-19T21:40:00Z',
  },
  {
    id: 'user-admin-jules',
    externalAuthId: 'clerk_jules',
    email: 'jules.adeyemi@sonartra.com',
    status: UserStatus.Active,
    kind: UserKind.InternalAdmin,
    profile: { firstName: 'Jules', lastName: 'Adeyemi', fullName: 'Jules Adeyemi', title: 'Customer Success Operations Manager', avatarUrl: null },
    internalAdminRole: InternalAdminRole.CustomerSuccessAdmin,
    primaryOrganisationId: null,
    recentActivity: { lastActiveAt: '2026-03-20T05:52:00Z', lastAuditEventId: 'audit-1005', lastAssessmentVersionId: null },
    createdAt: '2025-10-03T10:15:00Z',
    updatedAt: '2026-03-20T05:52:00Z',
  },
  {
    id: 'user-admin-ella',
    externalAuthId: 'clerk_ella',
    email: 'ella.wright@sonartra.com',
    status: UserStatus.Suspended,
    kind: UserKind.InternalAdmin,
    profile: { firstName: 'Ella', lastName: 'Wright', fullName: 'Ella Wright', title: 'Support Operations Analyst', avatarUrl: null },
    internalAdminRole: InternalAdminRole.SupportAdmin,
    primaryOrganisationId: null,
    recentActivity: { lastActiveAt: '2026-03-11T13:12:00Z', lastAuditEventId: 'audit-1001', lastAssessmentVersionId: null },
    createdAt: '2025-08-18T11:45:00Z',
    updatedAt: '2026-03-12T09:00:00Z',
  },
  {
    id: 'user-org-alex',
    externalAuthId: 'clerk_alex',
    email: 'alex.mercer@northstarlogistics.com',
    status: UserStatus.Active,
    kind: UserKind.OrganisationUser,
    profile: { firstName: 'Alex', lastName: 'Mercer', fullName: 'Alex Mercer', title: 'People Director', avatarUrl: null },
    internalAdminRole: null,
    primaryOrganisationId: 'org-northstar',
    recentActivity: { lastActiveAt: '2026-03-19T15:20:00Z', lastAuditEventId: 'audit-1004', lastAssessmentVersionId: null },
    createdAt: '2025-11-06T08:30:00Z',
    updatedAt: '2026-03-19T15:20:00Z',
  },
  {
    id: 'user-org-bianca',
    externalAuthId: 'clerk_bianca',
    email: 'bianca.ng@aurorahealthgroup.com',
    status: UserStatus.Active,
    kind: UserKind.OrganisationUser,
    profile: { firstName: 'Bianca', lastName: 'Ng', fullName: 'Bianca Ng', title: 'Chief Talent Officer', avatarUrl: null },
    internalAdminRole: null,
    primaryOrganisationId: 'org-aurora',
    recentActivity: { lastActiveAt: '2026-03-20T04:10:00Z', lastAuditEventId: 'audit-1006', lastAssessmentVersionId: null },
    createdAt: '2025-12-02T12:00:00Z',
    updatedAt: '2026-03-20T04:10:00Z',
  },
  {
    id: 'user-org-isaac',
    externalAuthId: null,
    email: 'isaac.reyes@vectorforge.io',
    status: UserStatus.Invited,
    kind: UserKind.OrganisationUser,
    profile: { firstName: 'Isaac', lastName: 'Reyes', fullName: 'Isaac Reyes', title: 'Operations Manager', avatarUrl: null },
    internalAdminRole: null,
    primaryOrganisationId: 'org-vectorforge',
    recentActivity: { lastActiveAt: null, lastAuditEventId: null, lastAssessmentVersionId: null },
    createdAt: '2026-03-14T16:05:00Z',
    updatedAt: '2026-03-14T16:05:00Z',
  },
  {
    id: 'user-org-maya',
    externalAuthId: 'clerk_maya',
    email: 'maya.holt@vectorforge.io',
    status: UserStatus.Deactivated,
    kind: UserKind.OrganisationUser,
    profile: { firstName: 'Maya', lastName: 'Holt', fullName: 'Maya Holt', title: 'Former Programme Lead', avatarUrl: null },
    internalAdminRole: null,
    primaryOrganisationId: 'org-vectorforge',
    recentActivity: { lastActiveAt: '2026-01-09T10:10:00Z', lastAuditEventId: 'audit-1002', lastAssessmentVersionId: null },
    createdAt: '2025-07-17T07:45:00Z',
    updatedAt: '2026-01-20T11:00:00Z',
  },
]

export const organisations: Organisation[] = [
  {
    id: 'org-northstar',
    slug: 'northstar-logistics',
    name: 'Northstar Logistics',
    status: OrganisationStatus.Active,
    plan: OrganisationPlan.Enterprise,
    sector: 'Logistics',
    region: 'United Kingdom',
    primaryContactUserId: 'user-org-alex',
    seatSummary: { purchased: 180, assigned: 148, invited: 6, available: 26 },
    enabledProducts: [
      { productKey: 'signals', label: 'Sonartra Signals', enabled: true, enabledAssessmentIds: ['assessment-signals'] },
      { productKey: 'team-dynamics', label: 'Team Dynamics', enabled: true, enabledAssessmentIds: ['assessment-team-dynamics'] },
    ],
    enabledAssessmentIds: ['assessment-signals', 'assessment-team-dynamics'],
    workspaceProvisionedAt: '2025-11-05T14:20:00Z',
    contractRenewalDate: '2026-11-30T00:00:00Z',
    lastActivityAt: '2026-03-19T16:04:00Z',
    createdAt: '2025-10-27T10:00:00Z',
    updatedAt: '2026-03-19T16:04:00Z',
  },
  {
    id: 'org-aurora',
    slug: 'aurora-health-group',
    name: 'Aurora Health Group',
    status: OrganisationStatus.Implementation,
    plan: OrganisationPlan.Enterprise,
    sector: 'Healthcare',
    region: 'United States',
    primaryContactUserId: 'user-org-bianca',
    seatSummary: { purchased: 240, assigned: 118, invited: 19, available: 103 },
    enabledProducts: [
      { productKey: 'signals', label: 'Sonartra Signals', enabled: true, enabledAssessmentIds: ['assessment-signals'] },
      { productKey: 'org-pulse', label: 'Organisation Pulse', enabled: true, enabledAssessmentIds: ['assessment-org-pulse'] },
    ],
    enabledAssessmentIds: ['assessment-signals', 'assessment-org-pulse'],
    workspaceProvisionedAt: '2026-02-12T09:10:00Z',
    contractRenewalDate: '2027-02-28T00:00:00Z',
    lastActivityAt: '2026-03-20T04:12:00Z',
    createdAt: '2026-01-18T13:40:00Z',
    updatedAt: '2026-03-20T04:12:00Z',
  },
  {
    id: 'org-vectorforge',
    slug: 'vectorforge-industrial',
    name: 'VectorForge Industrial',
    status: OrganisationStatus.Suspended,
    plan: OrganisationPlan.Growth,
    sector: 'Advanced Manufacturing',
    region: 'Germany',
    primaryContactUserId: 'user-org-isaac',
    seatSummary: { purchased: 75, assigned: 49, invited: 3, available: 23 },
    enabledProducts: [
      { productKey: 'signals', label: 'Sonartra Signals', enabled: true, enabledAssessmentIds: ['assessment-signals'] },
      { productKey: 'team-dynamics', label: 'Team Dynamics', enabled: false, enabledAssessmentIds: [] },
    ],
    enabledAssessmentIds: ['assessment-signals'],
    workspaceProvisionedAt: '2025-08-14T10:15:00Z',
    contractRenewalDate: '2026-08-31T00:00:00Z',
    lastActivityAt: '2026-02-07T09:48:00Z',
    createdAt: '2025-08-01T09:30:00Z',
    updatedAt: '2026-03-15T08:55:00Z',
  },
]

export const organisationMemberships: OrganisationMembership[] = [
  {
    id: 'membership-northstar-alex',
    organisationId: 'org-northstar',
    userId: 'user-org-alex',
    role: OrganisationRole.Owner,
    isBillingContact: true,
    isAssessmentContact: true,
    invitedAt: '2025-11-01T09:00:00Z',
    joinedAt: '2025-11-06T08:45:00Z',
    lastActiveAt: '2026-03-19T15:20:00Z',
    createdAt: '2025-11-01T09:00:00Z',
    updatedAt: '2026-03-19T15:20:00Z',
  },
  {
    id: 'membership-aurora-bianca',
    organisationId: 'org-aurora',
    userId: 'user-org-bianca',
    role: OrganisationRole.Admin,
    isBillingContact: false,
    isAssessmentContact: true,
    invitedAt: '2026-01-25T13:00:00Z',
    joinedAt: '2026-02-02T11:15:00Z',
    lastActiveAt: '2026-03-20T04:10:00Z',
    createdAt: '2026-01-25T13:00:00Z',
    updatedAt: '2026-03-20T04:10:00Z',
  },
  {
    id: 'membership-northstar-bianca',
    organisationId: 'org-northstar',
    userId: 'user-org-bianca',
    role: OrganisationRole.Analyst,
    isBillingContact: false,
    isAssessmentContact: false,
    invitedAt: '2026-03-01T09:30:00Z',
    joinedAt: '2026-03-03T10:00:00Z',
    lastActiveAt: '2026-03-18T17:25:00Z',
    createdAt: '2026-03-01T09:30:00Z',
    updatedAt: '2026-03-18T17:25:00Z',
  },
  {
    id: 'membership-vectorforge-isaac',
    organisationId: 'org-vectorforge',
    userId: 'user-org-isaac',
    role: OrganisationRole.Manager,
    isBillingContact: false,
    isAssessmentContact: true,
    invitedAt: '2026-03-14T16:05:00Z',
    joinedAt: null,
    lastActiveAt: null,
    createdAt: '2026-03-14T16:05:00Z',
    updatedAt: '2026-03-14T16:05:00Z',
  },
  {
    id: 'membership-vectorforge-maya',
    organisationId: 'org-vectorforge',
    userId: 'user-org-maya',
    role: OrganisationRole.Admin,
    isBillingContact: true,
    isAssessmentContact: false,
    invitedAt: '2025-07-18T12:00:00Z',
    joinedAt: '2025-07-22T09:10:00Z',
    lastActiveAt: '2026-01-09T10:10:00Z',
    createdAt: '2025-07-18T12:00:00Z',
    updatedAt: '2026-01-20T11:00:00Z',
  },
]

export const assessments: Assessment[] = [
  {
    id: 'assessment-signals',
    key: 'sonartra_signals',
    slug: 'sonartra-signals',
    title: 'Sonartra Signals',
    description: 'Core behavioural performance assessment for individual operating patterns and role fit.',
    category: AssessmentCategory.BehaviouralIntelligence,
    status: AssessmentStatus.Active,
    ownerUserId: 'user-admin-noah',
    currentLiveVersionId: 'av-signals-2-1',
    enabledOrganisationIds: ['org-northstar', 'org-aurora', 'org-vectorforge'],
    createdAt: '2025-07-10T09:00:00Z',
    updatedAt: '2026-03-20T06:45:00Z',
  },
  {
    id: 'assessment-team-dynamics',
    key: 'team_dynamics',
    slug: 'team-dynamics',
    title: 'Team Dynamics',
    description: 'Measures interaction patterns, friction hotspots, and collective execution tendencies.',
    category: AssessmentCategory.TeamDynamics,
    status: AssessmentStatus.Active,
    ownerUserId: 'user-admin-noah',
    currentLiveVersionId: 'av-team-1-0',
    enabledOrganisationIds: ['org-northstar'],
    createdAt: '2025-10-01T10:30:00Z',
    updatedAt: '2026-03-17T17:18:00Z',
  },
  {
    id: 'assessment-org-pulse',
    key: 'organisation_pulse',
    slug: 'organisation-pulse',
    title: 'Organisation Pulse',
    description: 'Tracks organisational conditions, alignment drift, and system-wide performance signals.',
    category: AssessmentCategory.OrganisationalPerformance,
    status: AssessmentStatus.Maintenance,
    ownerUserId: 'user-admin-rina',
    currentLiveVersionId: 'av-org-1-0',
    enabledOrganisationIds: ['org-aurora'],
    createdAt: '2025-12-15T14:00:00Z',
    updatedAt: '2026-03-18T12:40:00Z',
  },
]

export const assessmentVersions: AssessmentVersion[] = [
  {
    id: 'av-signals-2-2',
    assessmentId: 'assessment-signals',
    versionNumber: '2.2.0',
    status: AssessmentVersionStatus.Validated,
    publishStatus: PublishStatus.Scheduled,
    changelogSummary: 'Rebalanced stress interpretation thresholds and refreshed output narrative scaffolding.',
    questionCount: 84,
    scoringModelVersion: 'signals-score-v4',
    outputModelVersion: 'signals-output-v3',
    validationSummary: { ruleErrors: 0, ruleWarnings: 2, previewReady: true },
    publishTarget: { type: PublishTargetType.Global, description: 'Roll out globally to all enabled tenants after release review.' },
    createdBy: { userId: 'user-admin-noah', displayName: 'Noah Chen' },
    updatedBy: { userId: 'user-admin-noah', displayName: 'Noah Chen' },
    publishedBy: null,
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-03-19T21:40:00Z',
    submittedForReviewAt: '2026-03-14T09:15:00Z',
    validatedAt: '2026-03-18T15:20:00Z',
    publishedAt: null,
    archivedAt: null,
  },
  {
    id: 'av-signals-2-1',
    assessmentId: 'assessment-signals',
    versionNumber: '2.1.0',
    status: AssessmentVersionStatus.Live,
    publishStatus: PublishStatus.Published,
    changelogSummary: 'Current production baseline for core Signals scoring and reporting.',
    questionCount: 84,
    scoringModelVersion: 'signals-score-v4',
    outputModelVersion: 'signals-output-v2',
    validationSummary: { ruleErrors: 0, ruleWarnings: 0, previewReady: true },
    publishTarget: { type: PublishTargetType.Global, description: 'Live for all enabled tenants.' },
    createdBy: { userId: 'user-admin-rina', displayName: 'Rina Patel' },
    updatedBy: { userId: 'user-admin-noah', displayName: 'Noah Chen' },
    publishedBy: { userId: 'user-admin-rina', displayName: 'Rina Patel' },
    createdAt: '2026-01-10T09:20:00Z',
    updatedAt: '2026-02-03T11:00:00Z',
    submittedForReviewAt: '2026-01-18T12:00:00Z',
    validatedAt: '2026-01-26T16:45:00Z',
    publishedAt: '2026-02-03T11:00:00Z',
    archivedAt: null,
  },
  {
    id: 'av-signals-1-8',
    assessmentId: 'assessment-signals',
    versionNumber: '1.8.0',
    status: AssessmentVersionStatus.Archived,
    publishStatus: PublishStatus.RolledBack,
    changelogSummary: 'Superseded scoring calibration preserved for historical result traceability.',
    questionCount: 78,
    scoringModelVersion: 'signals-score-v3',
    outputModelVersion: 'signals-output-v1',
    validationSummary: { ruleErrors: 0, ruleWarnings: 1, previewReady: true },
    publishTarget: { type: PublishTargetType.Global, description: 'Historical production snapshot retained for result lineage.' },
    createdBy: { userId: 'user-admin-rina', displayName: 'Rina Patel' },
    updatedBy: { userId: 'user-admin-rina', displayName: 'Rina Patel' },
    publishedBy: { userId: 'user-admin-rina', displayName: 'Rina Patel' },
    createdAt: '2025-10-22T09:00:00Z',
    updatedAt: '2026-01-10T09:20:00Z',
    submittedForReviewAt: '2025-11-02T09:00:00Z',
    validatedAt: '2025-11-08T14:00:00Z',
    publishedAt: '2025-11-12T08:00:00Z',
    archivedAt: '2026-02-03T11:00:00Z',
  },
  {
    id: 'av-team-1-1',
    assessmentId: 'assessment-team-dynamics',
    versionNumber: '1.1.0',
    status: AssessmentVersionStatus.InReview,
    publishStatus: PublishStatus.Unpublished,
    changelogSummary: 'Adds facilitator summary output schema and team-level watchout weighting review.',
    questionCount: 52,
    scoringModelVersion: 'team-dynamics-score-v2',
    outputModelVersion: 'team-dynamics-output-v2',
    validationSummary: { ruleErrors: 1, ruleWarnings: 3, previewReady: false },
    publishTarget: { type: PublishTargetType.Organisation, organisationId: 'org-northstar', description: 'Stage for Northstar pilot after warning remediation.' },
    createdBy: { userId: 'user-admin-noah', displayName: 'Noah Chen' },
    updatedBy: { userId: 'user-admin-noah', displayName: 'Noah Chen' },
    publishedBy: null,
    createdAt: '2026-03-02T08:50:00Z',
    updatedAt: '2026-03-19T13:00:00Z',
    submittedForReviewAt: '2026-03-12T10:20:00Z',
    validatedAt: null,
    publishedAt: null,
    archivedAt: null,
  },
  {
    id: 'av-team-1-0',
    assessmentId: 'assessment-team-dynamics',
    versionNumber: '1.0.0',
    status: AssessmentVersionStatus.Live,
    publishStatus: PublishStatus.Published,
    changelogSummary: 'Initial production release for team execution and interaction diagnostics.',
    questionCount: 48,
    scoringModelVersion: 'team-dynamics-score-v1',
    outputModelVersion: 'team-dynamics-output-v1',
    validationSummary: { ruleErrors: 0, ruleWarnings: 0, previewReady: true },
    publishTarget: { type: PublishTargetType.Plan, organisationPlan: 'enterprise', description: 'Available for enterprise tenants with team reporting.' },
    createdBy: { userId: 'user-admin-noah', displayName: 'Noah Chen' },
    updatedBy: { userId: 'user-admin-noah', displayName: 'Noah Chen' },
    publishedBy: { userId: 'user-admin-rina', displayName: 'Rina Patel' },
    createdAt: '2025-11-20T11:00:00Z',
    updatedAt: '2026-01-15T12:30:00Z',
    submittedForReviewAt: '2025-12-04T10:10:00Z',
    validatedAt: '2025-12-10T16:40:00Z',
    publishedAt: '2026-01-15T12:30:00Z',
    archivedAt: null,
  },
  {
    id: 'av-org-1-0',
    assessmentId: 'assessment-org-pulse',
    versionNumber: '1.0.0',
    status: AssessmentVersionStatus.Live,
    publishStatus: PublishStatus.Paused,
    changelogSummary: 'Live enterprise baseline held pending refreshed validation evidence for healthcare rollout.',
    questionCount: 64,
    scoringModelVersion: 'org-pulse-score-v1',
    outputModelVersion: 'org-pulse-output-v1',
    validationSummary: { ruleErrors: 0, ruleWarnings: 2, previewReady: true },
    publishTarget: { type: PublishTargetType.Organisation, organisationId: 'org-aurora', description: 'Restricted to Aurora implementation cohort.' },
    createdBy: { userId: 'user-admin-rina', displayName: 'Rina Patel' },
    updatedBy: { userId: 'user-admin-rina', displayName: 'Rina Patel' },
    publishedBy: { userId: 'user-admin-rina', displayName: 'Rina Patel' },
    createdAt: '2026-02-14T15:00:00Z',
    updatedAt: '2026-03-18T12:40:00Z',
    submittedForReviewAt: '2026-02-18T09:20:00Z',
    validatedAt: '2026-02-24T13:00:00Z',
    publishedAt: '2026-02-27T17:30:00Z',
    archivedAt: null,
  },
]

export const auditLogEvents: AuditLogEvent[] = [
  {
    id: 'audit-1008',
    action: AuditAction.Published,
    actor: { userId: 'user-admin-rina', displayName: 'Rina Patel', email: 'rina.patel@sonartra.com', kind: UserKind.InternalAdmin },
    entity: { entityType: AuditEntityType.Release, entityId: 'av-signals-2-2', label: 'Sonartra Signals v2.2.0' },
    occurredAt: '2026-03-20T07:18:00Z',
    summary: 'Scheduled Sonartra Signals v2.2.0 for global publish window.',
    details: { publish_status: 'scheduled', target: 'global', warnings_remaining: 2 },
  },
  {
    id: 'audit-1007',
    action: AuditAction.Updated,
    actor: { userId: 'user-admin-noah', displayName: 'Noah Chen', email: 'noah.chen@sonartra.com', kind: UserKind.InternalAdmin },
    entity: { entityType: AuditEntityType.AssessmentVersion, entityId: 'av-team-1-1', label: 'Team Dynamics v1.1.0' },
    occurredAt: '2026-03-19T21:40:00Z',
    summary: 'Updated review notes after validation failed preview readiness checks.',
    details: { rule_errors: 1, preview_ready: false },
  },
  {
    id: 'audit-1006',
    action: AuditAction.RoleGranted,
    actor: { userId: 'user-admin-jules', displayName: 'Jules Adeyemi', email: 'jules.adeyemi@sonartra.com', kind: UserKind.InternalAdmin },
    entity: { entityType: AuditEntityType.Membership, entityId: 'membership-aurora-bianca', label: 'Aurora Health Group / Bianca Ng' },
    occurredAt: '2026-03-20T04:10:00Z',
    summary: 'Confirmed Aurora implementation sponsor as customer admin for rollout coordination.',
    details: { organisation_role: 'admin', organisation_id: 'org-aurora' },
  },
  {
    id: 'audit-1005',
    action: AuditAction.StatusChanged,
    actor: { userId: 'user-admin-jules', displayName: 'Jules Adeyemi', email: 'jules.adeyemi@sonartra.com', kind: UserKind.InternalAdmin },
    entity: { entityType: AuditEntityType.Organisation, entityId: 'org-vectorforge', label: 'VectorForge Industrial' },
    occurredAt: '2026-03-15T08:55:00Z',
    summary: 'Suspended tenant rollout pending overdue renewal and inactive sponsor replacement.',
    details: { previous_status: 'active', next_status: 'suspended' },
  },
  {
    id: 'audit-1004',
    action: AuditAction.SignIn,
    actor: { userId: 'user-org-alex', displayName: 'Alex Mercer', email: 'alex.mercer@northstarlogistics.com', kind: UserKind.OrganisationUser },
    entity: { entityType: AuditEntityType.User, entityId: 'user-org-alex', label: 'Alex Mercer' },
    occurredAt: '2026-03-19T15:20:00Z',
    summary: 'Customer owner signed in to review current assessment adoption.',
    details: { organisation_id: 'org-northstar' },
  },
  {
    id: 'audit-1002',
    action: AuditAction.RoleRevoked,
    actor: { userId: 'user-admin-rina', displayName: 'Rina Patel', email: 'rina.patel@sonartra.com', kind: UserKind.InternalAdmin },
    entity: { entityType: AuditEntityType.Membership, entityId: 'membership-vectorforge-maya', label: 'VectorForge Industrial / Maya Holt' },
    occurredAt: '2026-01-20T11:00:00Z',
    summary: 'Removed former programme lead from active tenant administration.',
    details: { organisation_role: 'admin', user_status: 'deactivated' },
  },
  {
    id: 'audit-1001',
    action: AuditAction.StatusChanged,
    actor: { userId: 'user-admin-rina', displayName: 'Rina Patel', email: 'rina.patel@sonartra.com', kind: UserKind.InternalAdmin },
    entity: { entityType: AuditEntityType.AdminAccess, entityId: 'user-admin-ella', label: 'Ella Wright' },
    occurredAt: '2026-03-12T09:00:00Z',
    summary: 'Suspended support operator pending access review.',
    details: { previous_status: 'active', next_status: 'suspended' },
  },
]

export const adminModuleCapabilityMap: Record<AdminModuleKey, AdminCapability> = {
  [AdminModuleKey.Dashboard]: AdminCapability.DashboardView,
  [AdminModuleKey.Organisations]: AdminCapability.OrganisationsView,
  [AdminModuleKey.Users]: AdminCapability.UsersView,
  [AdminModuleKey.Assessments]: AdminCapability.AssessmentsView,
  [AdminModuleKey.Releases]: AdminCapability.ReleasesView,
  [AdminModuleKey.Audit]: AdminCapability.AuditView,
}
